<?xml version="1.0" ?>
<robot name="box_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="robot_name" default="box_bot_X"/>
  <xacro:property name="robot_name_prop" value="$(arg robot_name)"/>


  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/materials.xacro" />
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/properties.xacro" />
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/macros.xacro" />
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/wheels.xacro" />
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/caster_wheels.xacro" />  
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/box_bot_body.xacro" />
  <xacro:include filename="$(find pechan_gazebo_sim)/description/robot/box_bot_gazebo.xacro" />
  <xacro:box_bot_sim robot_name="$(arg robot_name)"/>
  <!--
  <xacro:include filename="$(find box_bot_description)/robot/box_bot_propeller.xacro" />
  -->
  
  <xacro:box_bot_body parent_name="${base_name}"/>

  
  <!-- <xacro:link_wheel name="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" parent="${base_name}" child="right_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" />

  <xacro:link_wheel name="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" parent="${base_name}" child="left_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" /> -->

  <xacro:link_wheel name="right_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_right_wheel" parent="${base_name}" child="right_wheel" origin_xyz="0 ${-1.0 * base_box_x / 2.0} ${-1.0 * wheel_radius}" />

  <xacro:link_wheel name="left_wheel" r="${wheel_radius}" l="${wheel_width}" incr="${wheel_increment}"/>
  <xacro:joint_wheel name="joint_left_wheel" parent="${base_name}" child="left_wheel" origin_xyz="0 ${base_box_x / 2.0} ${-1.0 * wheel_radius}" />





  <xacro:caster_wheel parent="chassis" caster_wheel_name="front" origin_xyz="${(base_box_x / 2.0) - wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" length="${dummy_length}"/>
  <xacro:caster_wheel parent="chassis" caster_wheel_name="back" origin_xyz="${(-1.0 *base_box_x / 2.0) + wheel_increment} 0 ${-1.0* base_box_x / 2.0}" radius="${wheel_increment}" length="${dummy_length}"/>
  

</robot>
